
services:
  hewo_face:
    image: hewo_face:pygame
    container_name: hewo_face
    privileged: true
    ports:
      - "5000:5000"
    environment:
      DISPLAY: $DISPLAY
      PULSE_SERVER: 'unix:/run/user/1000/pulse/native'
    command: bash -c ". venv/bin/activate && echo $DISPLAY && hewo_main"
    volumes:
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
