services:
  hewo_face:
    build:
      context: .
      dockerfile: Dockerfile
    image: hewo_face:pygame
    container_name: hewo_face
    network_mode: host
    environment:
      DISPLAY: $DISPLAY
      PULSE_SERVER: 'unix:/run/user/1000/pulse/native'
    command: hewo_face_main
    volumes:
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    cpus: 1.0
    mem_limit: 0.5g

